language: python

python:
  - 3.6

services:
- docker

before_install:
  - pip install codecov coverage
  - pip install -r test_requirements.txt

install:
  - pip install -r requirements.txt

script:
  - PYTHONPATH=. coverage run -m unittest discover -v -s httpstatuspuppet/tests
  - coverage run setup.py -q install
  - coverage combine -a
  - coverage report

after_success:
  - codecov
